spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_portal
    username: job_portal
    password: j0bPort@l
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

